[package]
name = "aoc20-04"
version = "0.1.0"
authors = ["Manuel HÃ¤ssig <manuel@haessig.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6"
thiserror = "1.0"
